GET http://localhost:3000/articles

###
GET http://localhost:3000/articles?skip=0&take=2 

###
GET http://localhost:3000/articles/user/895

###
POST http://localhost:3000/articles
Content-Type: application/json 

 {
  "titre": "publication",          
  "contenu": "optionnel",            
  "published": true,
   "utilisateurId": 900
 }
###
PATCH  http://localhost:3000/articles/3
Content-Type: application/json 

 {
  
  "titre": "ruotexff",          
  "contenu": "optibttuuuuuuuuuuonnel",            
  "published": false,
  "utilisateurId": 4
 }
###
DELETE http://localhost:3000/articles/2482


