GET http://localhost:3000/users

###
GET http://localhost:3000/users/800

###
POST http://localhost:3000/users
Content-Type: application/json 

 {
   "nom":  "toto",   
  "email": "totii@gmail.com" , 
  "password": "0000",
  "role": "AUTHOR"
 }
###
PATCH  http://localhost:3000/users/795
Content-Type: application/json 

 {
  
  "nom":  "titi",   
  "email": "toto@gmail.com" , 
  "password": "200",
  "role": "ADMIN"
 }

###
DELETE http://localhost:3000/users/896


